const C=window.APP_CONFIG||{};const DEMO=C.DEMO_MODE!==false&&!C.SUPABASE_URL;const sb=!DEMO&&window.supabase?window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
let state={session:null,profile:null,workshop:null,customers:[],vehicles:[],quotes:[],appointments:[],shops:[],reviews:[]};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])), money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), uid=()=>crypto.randomUUID?.()||Date.now()+Math.random();
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function modal(h){$('#modalBox').innerHTML=h;$('#modal').classList.add('show')}function closeModal(){$('#modal').classList.remove('show')}
async function init(){if(DEMO){state.profile={role:'oficina',full_name:'Oficina Modelo'};state.workshop={name:'Oficina Modelo',city:'Joinville - SC',phone:'47999990000',services:['Revisão','Freios','Suspensão'],rating:4.8};state.shops=[state.workshop];render();return}const {data:{session}}=await sb.auth.getSession();state.session=session;if(session)await loadOnline();else renderLanding();sb.auth.onAuthStateChange(async(_,s)=>{state.session=s;if(s)await loadOnline();else renderLanding()})}
async function loadOnline(){const u=state.session.user;let p=await sb.from('profiles').select('*').eq('id',u.id).single();state.profile=p.data; if(state.profile?.role==='oficina'){let w=await sb.from('workshops').select('*').eq('owner_id',u.id).single();state.workshop=w.data;let [c,v,q,a]=await Promise.all([sb.from('customers').select('*').eq('owner_id',u.id),sb.from('vehicles').select('*').eq('owner_id',u.id),sb.from('quotes').select('*').eq('owner_id',u.id),sb.from('appointments').select('*').eq('owner_id',u.id)]);state.customers=c.data||[];state.vehicles=v.data||[];state.quotes=q.data||[];state.appointments=a.data||[]}else{let [v,q,a,s]=await Promise.all([sb.from('vehicles').select('*').eq('owner_id',u.id),sb.from('quotes').select('*').eq('owner_id',u.id),sb.from('appointments').select('*').eq('owner_id',u.id),sb.from('workshops').select('*').limit(50)]);state.vehicles=v.data||[];state.quotes=q.data||[];state.appointments=a.data||[];state.shops=s.data||[]}render()}
function account(){return state.session?`<span class="pill">${esc(state.profile?.full_name||state.session.user.email)}</span> <button class="btn ghost" onclick="logout()">Sair</button>`:`<button class="btn" onclick="auth()">Entrar / cadastrar</button>`}
function nav(items,active){return `<div class="tabs">${items.map(x=>`<button class="tab ${x[0]===active?'active':''}" onclick="route('${x[0]}')">${x[1]}</button>`).join('')}</div>`}
function render(){ $('#account').innerHTML=account(); if(!state.profile){renderLanding();return} $('#app').innerHTML=state.profile.role==='oficina'?shopPage('dashboard'):clientPage('home') }
function renderLanding(){ $('#app').innerHTML=`<div class="hero"><h1>Oficina Fácil + Mecânico Perto</h1><p>Gestão de oficina e conexão com motoristas em uma única plataforma.</p><div class="actions" style="margin-top:15px"><button class="btn" onclick="auth('oficina')">Sou oficina</button><button class="btn orange" onclick="auth('cliente')">Sou motorista</button></div></div><div class="grid"><div class="card"><h3>🔧 Gestão</h3><p>Clientes, veículos, orçamentos, serviços, agenda e financeiro.</p></div><div class="card"><h3>📍 Descoberta</h3><p>Motoristas encontram oficinas por localização e serviço.</p></div><div class="card"><h3>💬 Atendimento</h3><p>WhatsApp, solicitações de orçamento e agendamentos.</p></div><div class="card"><h3>⭐ Reputação</h3><p>Avaliações e perfil público para aumentar a confiança.</p></div></div><div class="footer">Modo demonstração. Para uso comercial, configure o Supabase conforme o README.</div>`}
function route(r){$('#app').innerHTML=state.profile.role==='oficina'?shopPage(r):clientPage(r)}
const shopTabs=[['dashboard','📊 Painel'],['clientes','👥 Clientes'],['veiculos','🚗 Veículos'],['orcamentos','🧾 Orçamentos'],['agenda','📅 Agenda'],['plano','⭐ Plano'],['config','⚙️ Config']];
function shopPage(r){if(r==='dashboard')return `<div class="hero"><h1>Oficina Fácil</h1><p>Organize sua oficina e acompanhe seus resultados.</p></div>${nav(shopTabs,r)}<div class="grid"><div class="card stat"><span class="muted">Clientes</span><b>${state.customers.length}</b></div><div class="card stat"><span class="muted">Veículos</span><b>${state.vehicles.length}</b></div><div class="card stat"><span class="muted">Orçamentos</span><b>${state.quotes.length}</b></div><div class="card stat"><span class="muted">Agendamentos</span><b>${state.appointments.length}</b></div></div><div class="section grid"><div class="card"><h3>Ações rápidas</h3><div class="actions"><button class="btn" onclick="customerForm()">+ Cliente</button><button class="btn secondary" onclick="vehicleForm()">+ Veículo</button><button class="btn secondary" onclick="quoteForm()">+ Orçamento</button></div></div><div class="card"><h3>Faturamento estimado</h3><div style="font-size:28px;font-weight:800">${money(state.quotes.reduce((a,q)=>a+Number(q.total||0),0))}</div></div></div>`;
if(r==='clientes')return listPage(shopTabs,r,'Clientes',state.customers.map(c=>`<div class="card"><div class="row"><div><b>${esc(c.name)}</b><div class="muted">${esc(c.phone||'')} ${esc(c.email||'')}</div></div><button class="btn ghost" onclick="vehicleForm('${c.id}')">+ Veículo</button></div></div>`).join(''),customerForm);
if(r==='veiculos')return listPage(shopTabs,r,'Veículos',state.vehicles.map(v=>`<div class="card row"><div><b>${esc(v.plate)} — ${esc(v.brand)} ${esc(v.model)}</b><div class="muted">${esc(v.year)} • ${esc(v.km)} km</div></div><button class="btn ghost" onclick="quoteForm('${v.id}')">Orçar</button></div>`).join(''),vehicleForm);
if(r==='orcamentos')return listPage(shopTabs,r,'Orçamentos',state.quotes.map(q=>`<div class="card"><div class="row"><div><b>${esc(q.title)}</b><div class="muted">${esc(q.vehicle||'')} </div></div><span class="tag ${q.status==='aprovado'?'ok':''}">${esc(q.status)}</span></div><h3>${money(q.total)}</h3><div class="actions"><button class="btn secondary" onclick="wa('${q.phone||''}','Olá! Seu orçamento ficou em ${money(q.total)}.')">WhatsApp</button></div></div>`).join(''),quoteForm);
if(r==='agenda')return listPage(shopTabs,r,'Agenda',state.appointments.map(a=>`<div class="card"><b>${esc(a.date)} ${esc(a.time)}</b><div>${esc(a.service||'Serviço')}</div><span class="tag">${esc(a.status||'agendado')}</span></div>`).join(''),appointmentForm);
if(r==='plano')return `<div class="hero"><h1>Plano da oficina</h1><p>Escolha o nível de recursos para crescer.</p></div>${nav(shopTabs,r)}<div class="grid"><div class="card"><h2>Grátis</h2><p>Perfil, clientes e recursos básicos.</p><h2>R$ 0</h2></div><div class="card"><h2>Premium</h2><p>Relatórios, destaque, mais limites e recursos comerciais.</p><h2>R$ 49,90/mês</h2><button class="btn" onclick="toast('Integração de assinatura pronta para configurar com Mercado Pago')">Assinar Premium</button></div></div>`;
return `<div class="hero"><h1>Configurações</h1><p>Perfil público da oficina.</p></div>${nav(shopTabs,r)}<div class="card"><b>${esc(state.workshop?.name||state.profile.full_name)}</b><p class="muted">${esc(state.workshop?.city||'')}</p><button class="btn" onclick="shopForm()">Editar perfil</button></div>`}
function listPage(tabs,r,title,list,add){return `<div class="hero"><h1>${title}</h1></div>${nav(tabs,r)}<div class="actions section"><button class="btn" onclick="${add.name}()">+ Adicionar</button></div><div class="list">${list||'<div class="card muted">Nenhum registro.</div>'}</div>`}
function clientPage(r){const tabs=[['home','🏠 Início'],['oficinas','📍 Oficinas'],['orcamentos','🧾 Orçamentos'],['agenda','📅 Agenda'],['veiculo','🚗 Meu carro'],['perfil','👤 Perfil']];if(r==='home')return `<div class="hero orange"><h1>Mecânico Perto</h1><p>Encontre oficinas, peça orçamento e agende seu atendimento.</p></div>${nav(tabs,r)}<div class="grid"><div class="card"><h3>📍 Oficinas</h3><p>Veja oficinas cadastradas e seus serviços.</p><button class="btn orange" onclick="route('oficinas')">Encontrar</button></div><div class="card"><h3>🧾 Orçamento</h3><p>Descreva o problema do seu carro.</p><button class="btn" onclick="clientQuoteForm()">Solicitar</button></div></div>`;if(r==='oficinas')return `<div class="hero orange"><h1>Oficinas</h1><p>Serviços, avaliação e contato.</p></div>${nav(tabs,r)}<div class="list">${state.shops.map(s=>`<div class="card"><div class="row"><div><h3>${esc(s.name)}</h3><div class="muted">${esc(s.city||'')}</div><div>⭐ ${esc(s.rating||'—')}</div></div><span class="tag ok">Ativa</span></div><p>${(s.services||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join(' ')}</p><div class="actions"><button class="btn orange" onclick="clientQuoteForm('${s.id}')">Pedir orçamento</button>${s.phone?`<button class="btn ghost" onclick="wa('${s.phone}','Olá! Encontrei sua oficina no Mecânico Perto.')">WhatsApp</button>`:''}</div></div>`).join('')||'<div class="card muted">Nenhuma oficina cadastrada ainda.</div>'}</div>`;if(r==='orcamentos')return `<div class="hero"><h1>Meus orçamentos</h1></div>${nav(tabs,r)}<div class="list">${state.quotes.map(q=>`<div class="card row"><div><b>${esc(q.title)}</b><div class="muted">${esc(q.vehicle||'')}</div></div><span class="tag">${esc(q.status)}</span></div>`).join('')||'<div class="card muted">Nenhum orçamento.</div>'}</div>`;if(r==='agenda')return `<div class="hero"><h1>Meus agendamentos</h1></div>${nav(tabs,r)}<div class="list">${state.appointments.map(a=>`<div class="card"><b>${esc(a.date)} ${esc(a.time)}</b><div>${esc(a.service||'')}</div></div>`).join('')||'<div class="card muted">Nenhum agendamento.</div>'}</div>`;if(r==='veiculo')return `<div class="hero"><h1>Meu carro</h1></div>${nav(tabs,r)}<div class="list">${state.vehicles.map(v=>`<div class="card"><h3>${esc(v.brand)} ${esc(v.model)}</h3><div class="muted">${esc(v.plate)} • ${esc(v.year)} • ${esc(v.km)} km</div></div>`).join('')||'<div class="card muted">Cadastre seu veículo pela opção abaixo.</div>'}</div><div class="section"><button class="btn orange" onclick="vehicleForm()">Cadastrar veículo</button></div>`;return `<div class="hero"><h1>Meu perfil</h1></div>${nav(tabs,r)}<div class="card"><b>${esc(state.profile.full_name||'Usuário')}</b><div class="muted">${esc(state.session?.user?.email||'')}</div></div>`}
function fields(title,fs,fn){modal(`<h2>${title}</h2><div class="form">${fs.map(f=>`<div class="${f.full?'full':''}"><label>${f.label}</label>${f.type==='select'?`<select id="f_${f.id}">${f.opts.map(o=>`<option value="${esc(o.value??o)}">${esc(o.label??o)}</option>`).join('')}</select>`:`<input id="f_${f.id}" type="${f.type||'text'}" placeholder="${esc(f.ph||'')}">`}</div>`).join('')}</div><div class="actions" style="margin-top:15px"><button class="btn" onclick="${fn}">Salvar</button><button class="btn ghost" onclick="closeModal()">Cancelar</button></div>`)}
const val=id=>document.getElementById('f_'+id)?.value||'';
function customerForm(){fields('Novo cliente',[{id:'name',label:'Nome'},{id:'phone',label:'WhatsApp'},{id:'email',label:'E-mail'}],'saveCustomer()')}async function saveCustomer(){let o={name:val('name'),phone:val('phone'),email:val('email')};if(DEMO)state.customers.push({...o,id:uid()});else{let r=await sb.from('customers').insert({owner_id:state.session.user.id,...o});if(r.error)return toast(r.error.message);await loadOnline()}closeModal();render();toast('Cliente salvo')}
function vehicleForm(cid){let opts=state.customers.map(c=>({value:c.id,label:c.name}));fields('Novo veículo',[{id:'customer_id',label:'Cliente',type:'select',opts:opts.length?opts:[{value:'',label:'Cliente'}]},{id:'plate',label:'Placa'},{id:'brand',label:'Marca'},{id:'model',label:'Modelo'},{id:'year',label:'Ano',type:'number'},{id:'km',label:'Quilometragem',type:'number'}],'saveVehicle()')}async function saveVehicle(){let o={owner_id:state.session.user.id,customer_id:val('customer_id')||null,plate:val('plate').toUpperCase(),brand:val('brand'),model:val('model'),year:Number(val('year')||0),km:Number(val('km')||0)};if(DEMO){state.vehicles.push({...o,id:uid()})}else{let r=await sb.from('vehicles').insert(o);if(r.error)return toast(r.error.message);await loadOnline()}closeModal();render();toast('Veículo salvo')}
function quoteForm(vid){fields('Novo orçamento',[{id:'title',label:'Serviço'},{id:'vehicle',label:'Veículo'},{id:'total',label:'Valor',type:'number'},{id:'phone',label:'WhatsApp'}],'saveQuote()')}async function saveQuote(){let o={owner_id:state.session.user.id,title:val('title'),vehicle:val('vehicle'),total:Number(val('total')||0),phone:val('phone'),status:'pendente'};if(DEMO)state.quotes.push({...o,id:uid()});else{let r=await sb.from('quotes').insert(o);if(r.error)return toast(r.error.message);await loadOnline()}closeModal();render();toast('Orçamento salvo')}
function appointmentForm(){fields('Novo agendamento',[{id:'date',label:'Data',type:'date'},{id:'time',label:'Horário',type:'time'},{id:'service',label:'Serviço'}],'saveAppointment()')}async function saveAppointment(){let o={owner_id:state.session.user.id,date:val('date'),time:val('time'),service:val('service'),status:'agendado'};if(DEMO)state.appointments.push({...o,id:uid()});else{let r=await sb.from('appointments').insert(o);if(r.error)return toast(r.error.message);await loadOnline()}closeModal();render();toast('Agendamento salvo')}
function clientQuoteForm(shopId){fields('Solicitar orçamento',[{id:'shop_id',label:'Oficina',type:'select',opts:state.shops.map(s=>({value:s.id,label:s.name}))},{id:'title',label:'Problema / serviço',full:true},{id:'vehicle',label:'Veículo'},{id:'phone',label:'WhatsApp'}],'saveClientQuote()')}async function saveClientQuote(){let o={owner_id:state.session.user.id,workshop_id:val('shop_id')||null,title:val('title'),vehicle:val('vehicle'),phone:val('phone'),status:'solicitado',total:0};if(DEMO)state.quotes.push({...o,id:uid()});else{let r=await sb.from('quotes').insert(o);if(r.error)return toast(r.error.message);await loadOnline()}closeModal();route('orcamentos');toast('Solicitação enviada')}
function shopForm(){fields('Perfil da oficina',[{id:'name',label:'Nome',ph:state.workshop?.name},{id:'city',label:'Cidade',ph:state.workshop?.city},{id:'phone',label:'WhatsApp',ph:state.workshop?.phone},{id:'services',label:'Serviços separados por vírgula',full:true}],'saveShop()')}async function saveShop(){let o={name:val('name'),city:val('city'),phone:val('phone'),services:val('services').split(',').map(x=>x.trim()).filter(Boolean)};if(DEMO)state.workshop={...state.workshop,...o};else{let r=await sb.from('workshops').update(o).eq('owner_id',state.session.user.id);if(r.error)return toast(r.error.message);await loadOnline()}closeModal();render();toast('Perfil atualizado')}
function wa(phone,msg){if(!phone)return toast('WhatsApp não informado');window.open('https://wa.me/'+phone.replace(/\D/g,'')+'?text='+encodeURIComponent(msg),'_blank')}
function auth(role){if(DEMO){modal(`<h2>Modo comercial</h2><p>Para usar contas reais, configure o Supabase no <b>config.js</b>. Enquanto isso, escolha um perfil de demonstração.</p><div class="actions"><button class="btn" onclick="demoLogin('oficina')">Oficina</button><button class="btn orange" onclick="demoLogin('cliente')">Motorista</button></div>`);return}modal(`<h2>Entrar / criar conta</h2><div class="form"><div class="full"><label>E-mail</label><input id="auth_email" type="email"></div><div class="full"><label>Senha</label><input id="auth_password" type="password"></div><div class="full"><label>Tipo</label><select id="auth_role"><option value="${role||'cliente'}">${role==='oficina'?'Oficina':'Motorista'}</option>${role?'':'<option value="oficina">Oficina</option><option value="cliente">Motorista</option>'}</select></div></div><div class="actions" style="margin-top:15px"><button class="btn" onclick="signup()">Criar conta</button><button class="btn ghost" onclick="signin()">Entrar</button></div>`)}
function demoLogin(role){state.profile={role,full_name:role==='oficina'?'Oficina Modelo':'Motorista Demo'};if(role==='cliente')state.shops=[{id:'demo1',name:'Oficina Modelo',city:'Joinville - SC',phone:'47999990000',services:['Revisão','Freios'],rating:4.8}];closeModal();render()}
async function signup(){let email=$('#auth_email').value,password=$('#auth_password').value,role=$('#auth_role').value;let r=await sb.auth.signUp({email,password,data:{role}});if(r.error)return toast(r.error.message);toast('Conta criada. Confirme seu e-mail se solicitado.');closeModal()}async function signin(){let r=await sb.auth.signInWithPassword({email:$('#auth_email').value,password:$('#auth_password').value});if(r.error)return toast(r.error.message);closeModal()}async function logout(){if(DEMO){state.profile=null;renderLanding();return}await sb.auth.signOut()}
init();
